import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import recupCitation from "./api/hello";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [citation, setCitation] = useState("");
  const [personnage, setPersonnage] = useState("");
  const [saison, setSaison] = useState("");

	const fetchData = () => {
		fetch("/api/hello")
			.then((res) => res.json())
			.then((data) => {
        setCitation(data.citation.citation);
        setPersonnage(data.citation.infos.personnage);
        setSaison(data.citation.infos.saison);
			})
			.catch((erreur) => console.error("Erreur lors de la requête : ", erreur));
  };

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<div>
					<h1 className={inter.className}>Bienvenue sur l'API de Kaamelott</h1>
					<button className={styles.btn} onClick={fetchData}>
						Afficher une citation
					</button>
					<table>
						<thead>
							<tr>
								<th>Citation</th>
								<th>Personnage</th>
								<th>Saison</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>{citation}</td>
								<td>{personnage}</td>
								<td>{saison}</td>
							</tr>
						</tbody>
					</table>
				</div>
			</main>
		</>
	);
}
